
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>exceptions &#8211; ビルトインエラークラス - Python Module of the Week</title>

<link rel="stylesheet" href="../_static/default.css" 
    type="text/css" />
<style>
    body {
        margin: 8px;
    }
    .highlight {
        background-color: white;
        border: 0;
    }
    .highlight pre {
        background-color: white;
    }
</style>

<link href="../_static/css/leaves.css" rel="stylesheet" type="text/css" />
<link rel="alternate" type="application/atom+xml"
      title="Doug Hellmann"
      href="http://feeds.feedburner.com/DougHellmann" />
<link rel="alternate" type="application/atom+xml"
      title="Doug Hellmann Project Releases"
      href="http://feeds.feedburner.com/DougHellmann-Releases" />
<link rel="alternate" type="application/atom+xml"
      title="Doug Hellmann Links"
      href="http://feeds.feedburner.com/DougHellmannLinkBlog" />



<script type="text/javascript">
  var DOCUMENTATION_OPTIONS = {
      URL_ROOT:    '../',
      VERSION:     '1.132',
      COLLAPSE_MODINDEX: false,
      FILE_SUFFIX: '.html'
  };
</script>

<script type="text/javascript" src="../_static/jquery.js"></script>
<script type="text/javascript" src="../_static/doctools.js"></script>
    <link rel="author" title="このドキュメントについて" href="../about.html" />
    <link rel="contents" title="コンテンツテーブル" href="../contents.html" />
    <link rel="index" title="インデックス" href="../genindex.html" />
    <link rel="top" title="Python Module of the Week" href="../index.html" />
    <link rel="up" title="組み込みブジェクト" href="../builtins.html" />
    <link rel="next" title="文字列サービス" href="../string_services.html" />
    <link rel="prev" title="組み込みブジェクト" href="../builtins.html" />

<meta name="verify-v1" content="5saTcOa2HLac4V85yUg3SARfun1PqT5Upu7IR/6fpv4="/>
</head>
<body>
    
<div id="container">
    
<div id="header">
  <a href="/"><h1>PyMOTW</h1></a>
  <p></p>
</div>

<div id="sidebar_left_wrapper">

<div id="navigation"> 
	<ul id="navlist">
		<li><a href="../index.html">ホーム</a></li>
		<li><a href="http://blog.doughellmann.com/" target="_">ブログ</a></li>
        <li><a href="http://www.doughellmann.com/books/">書籍</a></li>
		<li><a href="../about.html">自己紹介</a></li>
		<li><a href="/2/genindex.html">サイトインデックス</a></li>
	</ul>
</div>


  <div id="sidebar_left">
      <p>この情報が役に立つと思われたら、私の本を手に取ってみてください。
      <i><a href="/books/byexample/">The Python Standard Library By
      Example</a></i>.</p>
  </div>

</div>


<div id="sidebar">
  <h3>ページコンテンツ</h3>
  <ul>
<li><a class="reference internal" href="#">exceptions &#8211; ビルトインエラークラス</a><ul>
<li><a class="reference internal" href="#id1">説明</a></li>
<li><a class="reference internal" href="#id2">ベースクラス</a><ul>
<li><a class="reference internal" href="#baseexception">BaseException</a></li>
<li><a class="reference internal" href="#exception">Exception</a></li>
<li><a class="reference internal" href="#standarderror">StandardError</a></li>
<li><a class="reference internal" href="#arithmeticerror">ArithmeticError</a></li>
<li><a class="reference internal" href="#lookuperror">LookupError</a></li>
<li><a class="reference internal" href="#environmenterror">EnvironmentError</a></li>
</ul>
</li>
<li><a class="reference internal" href="#id3">例外を発生させる</a><ul>
<li><a class="reference internal" href="#assertionerror">AssertionError</a></li>
<li><a class="reference internal" href="#attributeerror">AttributeError</a></li>
<li><a class="reference internal" href="#eoferror">EOFError</a></li>
<li><a class="reference internal" href="#floatingpointerror">FloatingPointError</a></li>
<li><a class="reference internal" href="#generatorexit">GeneratorExit</a></li>
<li><a class="reference internal" href="#ioerror">IOError</a></li>
<li><a class="reference internal" href="#importerror">ImportError</a></li>
<li><a class="reference internal" href="#indexerror">IndexError</a></li>
<li><a class="reference internal" href="#keyerror">KeyError</a></li>
<li><a class="reference internal" href="#keyboardinterrupt">KeyboardInterrupt</a></li>
<li><a class="reference internal" href="#memoryerror">MemoryError</a></li>
<li><a class="reference internal" href="#nameerror">NameError</a></li>
<li><a class="reference internal" href="#notimplementederror">NotImplementedError</a></li>
<li><a class="reference internal" href="#oserror">OSError</a></li>
<li><a class="reference internal" href="#overflowerror">OverflowError</a></li>
<li><a class="reference internal" href="#referenceerror">ReferenceError</a></li>
<li><a class="reference internal" href="#runtimeerror">RuntimeError</a></li>
<li><a class="reference internal" href="#stopiteration">StopIteration</a></li>
<li><a class="reference internal" href="#syntaxerror">SyntaxError</a></li>
<li><a class="reference internal" href="#systemerror">SystemError</a></li>
<li><a class="reference internal" href="#systemexit">SystemExit</a></li>
<li><a class="reference internal" href="#typeerror">TypeError</a></li>
<li><a class="reference internal" href="#unboundlocalerror">UnboundLocalError</a></li>
<li><a class="reference internal" href="#unicodeerror">UnicodeError</a></li>
<li><a class="reference internal" href="#valueerror">ValueError</a></li>
<li><a class="reference internal" href="#zerodivisionerror">ZeroDivisionError</a></li>
</ul>
</li>
<li><a class="reference internal" href="#id5">警告のカテゴリ</a></li>
</ul>
</li>
</ul>
    <h3>ナビゲーション</h3>
      <p>
    <a href="../contents.html"><strong>コンテンツテーブル</strong></a><br/>
    
          <a href="../builtins.html" title="前の章へ"><strong>前:</strong> 組み込みブジェクト</a><br/>
          <a href="../string_services.html" title="次の章へ"><strong>次:</strong> 文字列サービス</a><br/>
      </p>
    
      <h3>This Page</h3>
      <p>
      <a href="../_sources/exceptions/index.txt"
               rel="nofollow">Show Source</a>
      </p><h3>サンプルプログラム</h3>

<p>PyMOTW の全てのサンプルプログラムの出力は、
注記されていない限りは Python 2.7.2 で生成されています。
標準ライブラリの初期のバージョンでは利用できない機能も紹介している
可能性があります。</p><p><iframe src="http://rcm.amazon.com/e/cm?lt1=_blank&bc1=000000&IS2=1&bg1=DDDDDD&fc1=000000&lc1=CC6714&t=hellflynet-20&o=1&p=8&l=as1&m=amazon&f=ifr&md=10FE9736YVPPT7A0FBG2&asins=0321767349" style="width:120px;height:240px;margin:0 1em 0 1em;" scrolling="no" frameborder="0"></iframe></p>    <p class="ads">
    <script type="text/javascript"><!--
    google_ad_client = "pub-3205160560229413";
    google_ad_width = 120;
    google_ad_height = 600;
    google_ad_format = "120x600_as";
    google_ad_type = "text";
    //2007-10-27: www.doughellmann.com
    google_ad_channel = "0828653884";
    google_color_border = "FFFFFF";
    google_color_bg = "FFFFFF";
    google_color_link = "CC6714";
    google_color_text = "000000";
    google_color_url = "999999";
    google_ui_features = "rc:0";
    //-->
    </script>
    <script type="text/javascript"
      src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
    </script>
    </p>
</div>


<div id="content">

    <div class="related">
      <h3>Navigation</h3>
      <ul>
        <li class="right" style="margin-right: 10px">
          <a href="../genindex.html" title="General Index"
             accesskey="I">index</a></li>
        <li class="right" >
          <a href="../py-modindex.html" title="Python Module Index"
             >modules</a> |</li>
        <li class="right" >
          <a href="../string_services.html" title="文字列サービス"
             accesskey="N">next</a> |</li>
        <li class="right" >
          <a href="../builtins.html" title="組み込みブジェクト"
             accesskey="P">previous</a> |</li>
        <li><a href="../contents.html">PyMOTW</a> &raquo;</li>
          <li><a href="../builtins.html" accesskey="U">組み込みブジェクト</a> &raquo;</li> 
      </ul>
    </div>

  <div class="section" id="exceptions">
<h1>exceptions &#8211; ビルトインエラークラス<a class="headerlink" href="#exceptions" title="Permalink to this headline">¶</a></h1>
<span class="target" id="module-exceptions"></span><table class="docutils field-list" frame="void" rules="none">
<col class="field-name" />
<col class="field-body" />
<tbody valign="top">
<tr class="field"><th class="field-name">目的:</th><td class="field-body">例外モジュールはインタープリタや標準ライブラリで使用されるビルトインエラーを定義する</td>
</tr>
<tr class="field"><th class="field-name">利用できるバージョン:</th><td class="field-body">1.5 以上</td>
</tr>
</tbody>
</table>
<div class="section" id="id1">
<h2>説明<a class="headerlink" href="#id1" title="Permalink to this headline">¶</a></h2>
<p>これまでに Python はクラス同様に例外として単純な文字列のメッセージに対応していました。Python 1.5 以降、全ての標準ライブラリモジュールはクラス例外を使用します。Python 2.5 を使用すると文字列例外は DeprecationWarning を発生させます。そして、文字列例外のサポートは今後廃止される予定です。</p>
</div>
<div class="section" id="id2">
<h2>ベースクラス<a class="headerlink" href="#id2" title="Permalink to this headline">¶</a></h2>
<p>例外クラスは階層構造で定義されていて、標準ライブラリドキュメントに説明があります。明らかな階層化の利点に加えて、継承された例外のベースクラスを捕捉することで関連する例外をまとめて捕捉できるので例外の継承は役に立ちます。大半のケースでは、ベースクラスは直接発生させることを目的としていません。</p>
<div class="section" id="baseexception">
<h3>BaseException<a class="headerlink" href="#baseexception" title="Permalink to this headline">¶</a></h3>
<p>全ての例外のベースクラスです。そのコンストラクタへ渡される引数から str() を使用してその例外の説明メッセージを作成するロジックを実装してください。</p>
</div>
<div class="section" id="exception">
<h3>Exception<a class="headerlink" href="#exception" title="Permalink to this headline">¶</a></h3>
<p>実行中のアプリケーションを終了させない例外のためのベースクラスです。全てのユーザ定義の例外はベースクラスとして Exception を使用すべきです。</p>
</div>
<div class="section" id="standarderror">
<h3>StandardError<a class="headerlink" href="#standarderror" title="Permalink to this headline">¶</a></h3>
<p>ビルトイン例外のベースクラスは標準ライブラリで使用されます。</p>
</div>
<div class="section" id="arithmeticerror">
<h3>ArithmeticError<a class="headerlink" href="#arithmeticerror" title="Permalink to this headline">¶</a></h3>
<p>数値関連のエラーのためのベースクラスです。</p>
</div>
<div class="section" id="lookuperror">
<h3>LookupError<a class="headerlink" href="#lookuperror" title="Permalink to this headline">¶</a></h3>
<p>何かを発見したときに発生させるエラーのベースクラスです。</p>
</div>
<div class="section" id="environmenterror">
<h3>EnvironmentError<a class="headerlink" href="#environmenterror" title="Permalink to this headline">¶</a></h3>
<p>Python の外部(オペレーティングシステム、ファイルシステム等)から発生するエラーのためのベースクラスです。</p>
</div>
</div>
<div class="section" id="id3">
<h2>例外を発生させる<a class="headerlink" href="#id3" title="Permalink to this headline">¶</a></h2>
<div class="section" id="assertionerror">
<span id="exceptions-assertionerror"></span><h3>AssertionError<a class="headerlink" href="#assertionerror" title="Permalink to this headline">¶</a></h3>
<p><tt class="docutils literal"><span class="pre">assert</span></tt> 文が失敗したときに AssertionError が発生します。</p>
<div class="highlight-python"><div class="highlight"><pre><span class="k">assert</span> <span class="bp">False</span><span class="p">,</span> <span class="s">&#39;The assertion failed&#39;</span>
</pre></div>
</div>
<div class="highlight-python"><pre>$ python exceptions_AssertionError_assert.py
Traceback (most recent call last):
  File "exceptions_AssertionError_assert.py", line 12, in &lt;module&gt;
    assert False, 'The assertion failed'
AssertionError: The assertion failed</pre>
</div>
<p><tt class="docutils literal"><span class="pre">failIf()</span></tt> のようなメソッドで <a class="reference internal" href="../unittest/index.html#module-unittest" title="Automated testing framework"><tt class="xref py py-mod docutils literal"><span class="pre">unittest</span></tt></a> モジュールでも使用されます。</p>
<div class="highlight-python"><div class="highlight"><pre><span class="kn">import</span> <span class="nn">unittest</span>

<span class="k">class</span> <span class="nc">AssertionExample</span><span class="p">(</span><span class="n">unittest</span><span class="o">.</span><span class="n">TestCase</span><span class="p">):</span>
    
    <span class="k">def</span> <span class="nf">test</span><span class="p">(</span><span class="bp">self</span><span class="p">):</span>
        <span class="bp">self</span><span class="o">.</span><span class="n">failUnless</span><span class="p">(</span><span class="bp">False</span><span class="p">)</span>

<span class="n">unittest</span><span class="o">.</span><span class="n">main</span><span class="p">()</span>
</pre></div>
</div>
<div class="highlight-python"><pre>$ python exceptions_AssertionError_unittest.py
F
======================================================================
FAIL: test (__main__.AssertionExample)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "exceptions_AssertionError_unittest.py", line 17, in test
    self.failUnless(False)
AssertionError: False is not true

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (failures=1)</pre>
</div>
</div>
<div class="section" id="attributeerror">
<span id="exceptions-attributeerror"></span><h3>AttributeError<a class="headerlink" href="#attributeerror" title="Permalink to this headline">¶</a></h3>
<p>属性の参照か割り当てが失敗したときに AttributeError が発生します。例えば、存在しない属性を参照しようとしたときに発生します。</p>
<div class="highlight-python"><div class="highlight"><pre><span class="k">class</span> <span class="nc">NoAttributes</span><span class="p">(</span><span class="nb">object</span><span class="p">):</span>
    <span class="k">pass</span>

<span class="n">o</span> <span class="o">=</span> <span class="n">NoAttributes</span><span class="p">()</span>
<span class="k">print</span> <span class="n">o</span><span class="o">.</span><span class="n">attribute</span>
</pre></div>
</div>
<div class="highlight-python"><pre>$ python exceptions_AttributeError.py
Traceback (most recent call last):
  File "exceptions_AttributeError.py", line 16, in &lt;module&gt;
    print o.attribute
AttributeError: 'NoAttributes' object has no attribute 'attribute'</pre>
</div>
<p>又は読み込み専用属性を変更しようとしたときに発生します。</p>
<div class="highlight-python"><div class="highlight"><pre><span class="k">class</span> <span class="nc">MyClass</span><span class="p">(</span><span class="nb">object</span><span class="p">):</span>
    
    <span class="nd">@property</span>
    <span class="k">def</span> <span class="nf">attribute</span><span class="p">(</span><span class="bp">self</span><span class="p">):</span>
        <span class="k">return</span> <span class="s">&#39;This is the attribute value&#39;</span>

<span class="n">o</span> <span class="o">=</span> <span class="n">MyClass</span><span class="p">()</span>
<span class="k">print</span> <span class="n">o</span><span class="o">.</span><span class="n">attribute</span>
<span class="n">o</span><span class="o">.</span><span class="n">attribute</span> <span class="o">=</span> <span class="s">&#39;New value&#39;</span>
</pre></div>
</div>
<div class="highlight-python"><pre>$ python exceptions_AttributeError_assignment.py
This is the attribute value
Traceback (most recent call last):
  File "exceptions_AttributeError_assignment.py", line 20, in &lt;module&gt;
    o.attribute = 'New value'
AttributeError: can't set attribute</pre>
</div>
</div>
<div class="section" id="eoferror">
<h3>EOFError<a class="headerlink" href="#eoferror" title="Permalink to this headline">¶</a></h3>
<p><tt class="docutils literal"><span class="pre">input()</span></tt> 又は <tt class="docutils literal"><span class="pre">raw_input()</span></tt> のようなビルトイン関数が入力ストリームの最後に遭遇する前にデータを読み込めないときに EOFError が発生します。 <tt class="docutils literal"><span class="pre">read()</span></tt> のような file メソッドはファイルの最後で空文字列を返します。</p>
<div class="highlight-python"><div class="highlight"><pre><span class="k">while</span> <span class="bp">True</span><span class="p">:</span>
    <span class="n">data</span> <span class="o">=</span> <span class="nb">raw_input</span><span class="p">(</span><span class="s">&#39;prompt:&#39;</span><span class="p">)</span>
    <span class="k">print</span> <span class="s">&#39;READ:&#39;</span><span class="p">,</span> <span class="n">data</span>
</pre></div>
</div>
<div class="highlight-python"><pre>$ echo hello | python PyMOTW/exceptions/exceptions_EOFError.py
prompt:READ: hello
prompt:Traceback (most recent call last):
  File "PyMOTW/exceptions/exceptions_EOFError.py", line 13, in &lt;module&gt;
    data = raw_input('prompt:')
EOFError: EOF when reading a line</pre>
</div>
</div>
<div class="section" id="floatingpointerror">
<h3>FloatingPointError<a class="headerlink" href="#floatingpointerror" title="Permalink to this headline">¶</a></h3>
<p>浮動小数点例外制御(fpectl)がオンのとき、最終的にエラーを引き起こす浮動小数点の操作で発生します。 <tt class="xref py py-mod docutils literal"><span class="pre">fpectl</span></tt> を有効にするには <tt class="docutils literal"><span class="pre">--with-fpectl</span></tt> フラグをセットしてコンパイルされたインタープリタが必要です。 <tt class="xref py py-mod docutils literal"><span class="pre">fpectl</span></tt> を使用することは <a class="reference external" href="http://docs.python.org/lib/module-fpectl.html">標準ライブラリドキュメントでは推奨されていません</a> 。</p>
<div class="highlight-python"><div class="highlight"><pre><span class="kn">import</span> <span class="nn">math</span>
<span class="kn">import</span> <span class="nn">fpectl</span>

<span class="k">print</span> <span class="s">&#39;Control off:&#39;</span><span class="p">,</span> <span class="n">math</span><span class="o">.</span><span class="n">exp</span><span class="p">(</span><span class="mi">1000</span><span class="p">)</span>
<span class="n">fpectl</span><span class="o">.</span><span class="n">turnon_sigfpe</span><span class="p">()</span>
<span class="k">print</span> <span class="s">&#39;Control on:&#39;</span><span class="p">,</span> <span class="n">math</span><span class="o">.</span><span class="n">exp</span><span class="p">(</span><span class="mi">1000</span><span class="p">)</span>
</pre></div>
</div>
</div>
<div class="section" id="generatorexit">
<h3>GeneratorExit<a class="headerlink" href="#generatorexit" title="Permalink to this headline">¶</a></h3>
<p>ジェネレータの <tt class="docutils literal"><span class="pre">close()</span></tt> メソッドが呼ばれるときにジェネレータ内部で発生します。</p>
<div class="highlight-python"><div class="highlight"><pre><span class="k">def</span> <span class="nf">my_generator</span><span class="p">():</span>
    <span class="k">try</span><span class="p">:</span>
        <span class="k">for</span> <span class="n">i</span> <span class="ow">in</span> <span class="nb">range</span><span class="p">(</span><span class="mi">5</span><span class="p">):</span>
            <span class="k">print</span> <span class="s">&#39;Yielding&#39;</span><span class="p">,</span> <span class="n">i</span>
            <span class="k">yield</span> <span class="n">i</span>
    <span class="k">except</span> <span class="ne">GeneratorExit</span><span class="p">:</span>
        <span class="k">print</span> <span class="s">&#39;Exiting early&#39;</span>

<span class="n">g</span> <span class="o">=</span> <span class="n">my_generator</span><span class="p">()</span>
<span class="k">print</span> <span class="n">g</span><span class="o">.</span><span class="n">next</span><span class="p">()</span>
<span class="n">g</span><span class="o">.</span><span class="n">close</span><span class="p">()</span>
</pre></div>
</div>
<div class="highlight-python"><pre>$ python exceptions_GeneratorExit.py
Yielding 0
0
Exiting early</pre>
</div>
</div>
<div class="section" id="ioerror">
<span id="exceptions-ioerror"></span><h3>IOError<a class="headerlink" href="#ioerror" title="Permalink to this headline">¶</a></h3>
<p>入力や出力が失敗するときに発生します。例えば、ディスクがいっぱいだったり、入力ファイルが存在しないときに発生します。</p>
<div class="highlight-python"><div class="highlight"><pre><span class="n">f</span> <span class="o">=</span> <span class="nb">open</span><span class="p">(</span><span class="s">&#39;/does/not/exist&#39;</span><span class="p">,</span> <span class="s">&#39;r&#39;</span><span class="p">)</span>
</pre></div>
</div>
<div class="highlight-python"><pre>$ python exceptions_IOError.py
Traceback (most recent call last):
  File "exceptions_IOError.py", line 12, in &lt;module&gt;
    f = open('/does/not/exist', 'r')
IOError: [Errno 2] No such file or directory: '/does/not/exist'</pre>
</div>
</div>
<div class="section" id="importerror">
<span id="exceptions-importerror"></span><h3>ImportError<a class="headerlink" href="#importerror" title="Permalink to this headline">¶</a></h3>
<p>あるモジュール、又はモジュールのメンバがインポートできないときに発生します。ImportError が発生する個所には複数の条件があります。</p>
<ol class="arabic simple">
<li>モジュールが存在しない場合</li>
</ol>
<div class="highlight-python"><div class="highlight"><pre><span class="kn">import</span> <span class="nn">module_does_not_exist</span>
</pre></div>
</div>
<div class="highlight-python"><pre>$ python exceptions_ImportError_nomodule.py
Traceback (most recent call last):
  File "exceptions_ImportError_nomodule.py", line 12, in &lt;module&gt;
    import module_does_not_exist
ImportError: No module named module_does_not_exist</pre>
</div>
<ol class="arabic simple" start="2">
<li><tt class="docutils literal"><span class="pre">from</span> <span class="pre">X</span> <span class="pre">import</span> <span class="pre">Y</span></tt> が使用されてモジュール X の内部で Y が見つからなかった場合</li>
</ol>
<div class="highlight-python"><div class="highlight"><pre><span class="kn">from</span> <span class="nn">exceptions</span> <span class="kn">import</span> <span class="n">MadeUpName</span>
</pre></div>
</div>
<div class="highlight-python"><pre>$ python exceptions_ImportError_missingname.py
Traceback (most recent call last):
  File "exceptions_ImportError_missingname.py", line 12, in &lt;module&gt;
    from exceptions import MadeUpName
ImportError: cannot import name MadeUpName</pre>
</div>
</div>
<div class="section" id="indexerror">
<h3>IndexError<a class="headerlink" href="#indexerror" title="Permalink to this headline">¶</a></h3>
<p>IndexError はシーケンスの範囲外を参照したときに発生します。</p>
<div class="highlight-python"><div class="highlight"><pre><span class="n">my_seq</span> <span class="o">=</span> <span class="p">[</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">1</span><span class="p">,</span> <span class="mi">2</span> <span class="p">]</span>
<span class="k">print</span> <span class="n">my_seq</span><span class="p">[</span><span class="mi">3</span><span class="p">]</span>
</pre></div>
</div>
<div class="highlight-python"><pre>$ python exceptions_IndexError.py
Traceback (most recent call last):
  File "exceptions_IndexError.py", line 13, in &lt;module&gt;
    print my_seq[3]
IndexError: list index out of range</pre>
</div>
</div>
<div class="section" id="keyerror">
<span id="exceptions-keyerror"></span><h3>KeyError<a class="headerlink" href="#keyerror" title="Permalink to this headline">¶</a></h3>
<p>同様に KeyError は辞書のキーが見つからなかったときに発生します。</p>
<div class="highlight-python"><div class="highlight"><pre><span class="n">d</span> <span class="o">=</span> <span class="p">{</span> <span class="s">&#39;a&#39;</span><span class="p">:</span><span class="mi">1</span><span class="p">,</span> <span class="s">&#39;b&#39;</span><span class="p">:</span><span class="mi">2</span> <span class="p">}</span>
<span class="k">print</span> <span class="n">d</span><span class="p">[</span><span class="s">&#39;c&#39;</span><span class="p">]</span>
</pre></div>
</div>
<div class="highlight-python"><pre>$ python exceptions_KeyError.py
Traceback (most recent call last):
  File "exceptions_KeyError.py", line 13, in &lt;module&gt;
    print d['c']
KeyError: 'c'</pre>
</div>
</div>
<div class="section" id="keyboardinterrupt">
<span id="exceptions-keyboardinterrupt"></span><h3>KeyboardInterrupt<a class="headerlink" href="#keyboardinterrupt" title="Permalink to this headline">¶</a></h3>
<p>ユーザが実行中のプログラムを停止するために Ctrl-C (又は Delete) を押下すると KeyboardInterrupt が発生します。その他のほとんどの例外と違い、Exception を捕捉するグローバルな例外ハンドラによって捕捉されないように KeyboardInterrupt は BaseException から直接継承します。</p>
<div class="highlight-python"><div class="highlight"><pre><span class="k">try</span><span class="p">:</span>
    <span class="k">print</span> <span class="s">&#39;Press Return or Ctrl-C:&#39;</span><span class="p">,</span>
    <span class="n">ignored</span> <span class="o">=</span> <span class="nb">raw_input</span><span class="p">()</span>
<span class="k">except</span> <span class="ne">Exception</span><span class="p">,</span> <span class="n">err</span><span class="p">:</span>
    <span class="k">print</span> <span class="s">&#39;Caught exception:&#39;</span><span class="p">,</span> <span class="n">err</span>
<span class="k">except</span> <span class="ne">KeyboardInterrupt</span><span class="p">,</span> <span class="n">err</span><span class="p">:</span>
    <span class="k">print</span> <span class="s">&#39;Caught KeyboardInterrupt&#39;</span>
<span class="k">else</span><span class="p">:</span>
    <span class="k">print</span> <span class="s">&#39;No exception&#39;</span>
</pre></div>
</div>
<p>プロンプトで Ctrl-C を押下すると KeyboardInterrupt 例外を引き起こします。</p>
<div class="highlight-python"><pre>$ python exceptions_KeyboardInterrupt.py
Press Return or Ctrl-C: ^CCaught KeyboardInterrupt</pre>
</div>
</div>
<div class="section" id="memoryerror">
<h3>MemoryError<a class="headerlink" href="#memoryerror" title="Permalink to this headline">¶</a></h3>
<p>実行中のプログラムがメモリ不足になったら、MemoryError を発生させてリカバリ(例えば、オブジェクトを削除する)することができます。</p>
<div class="highlight-python"><div class="highlight"><pre><span class="kn">import</span> <span class="nn">itertools</span>

<span class="c"># 大量のメモリを割り当てることで MemoryError の発生を試みる</span>
<span class="n">l</span> <span class="o">=</span> <span class="p">[]</span>
<span class="k">for</span> <span class="n">i</span> <span class="ow">in</span> <span class="nb">range</span><span class="p">(</span><span class="mi">3</span><span class="p">):</span>
    <span class="k">try</span><span class="p">:</span>
        <span class="k">for</span> <span class="n">j</span> <span class="ow">in</span> <span class="n">itertools</span><span class="o">.</span><span class="n">count</span><span class="p">(</span><span class="mi">1</span><span class="p">):</span>
            <span class="k">print</span> <span class="n">i</span><span class="p">,</span> <span class="n">j</span>
            <span class="n">l</span><span class="o">.</span><span class="n">append</span><span class="p">(</span><span class="s">&#39;*&#39;</span> <span class="o">*</span> <span class="p">(</span><span class="mi">2</span><span class="o">**</span><span class="mi">30</span><span class="p">))</span>
    <span class="k">except</span> <span class="ne">MemoryError</span><span class="p">:</span>
        <span class="k">print</span> <span class="s">&#39;(error, discarding existing list)&#39;</span>
        <span class="n">l</span> <span class="o">=</span> <span class="p">[]</span>
</pre></div>
</div>
<div class="highlight-python"><pre>$ python exceptions_MemoryError.py
python(49670) malloc: *** mmap(size=1073745920) failed (error code=12)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug
python(49670) malloc: *** mmap(size=1073745920) failed (error code=12)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug
python(49670) malloc: *** mmap(size=1073745920) failed (error code=12)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug
0 1
0 2
0 3
(error, discarding existing list)
1 1
1 2
1 3
(error, discarding existing list)
2 1
2 2
2 3
(error, discarding existing list)</pre>
</div>
</div>
<div class="section" id="nameerror">
<h3>NameError<a class="headerlink" href="#nameerror" title="Permalink to this headline">¶</a></h3>
<p>カレントスコープに存在しない名前を参照するときに NameErrors が発生します。例えば、資格のない変数名です。</p>
<div class="highlight-python"><div class="highlight"><pre><span class="k">def</span> <span class="nf">func</span><span class="p">():</span>
    <span class="k">print</span> <span class="n">unknown_name</span>

<span class="n">func</span><span class="p">()</span>
</pre></div>
</div>
<div class="highlight-python"><pre>$ python exceptions_NameError.py
Traceback (most recent call last):
  File "exceptions_NameError.py", line 15, in &lt;module&gt;
    func()
  File "exceptions_NameError.py", line 13, in func
    print unknown_name
NameError: global name 'unknown_name' is not defined</pre>
</div>
</div>
<div class="section" id="notimplementederror">
<span id="exceptions-notimplementederror"></span><h3>NotImplementedError<a class="headerlink" href="#notimplementederror" title="Permalink to this headline">¶</a></h3>
<p>サブクラスで定義する必要のあるメソッド又は振る舞いを表すために、 <em>インタフェース</em> を模倣してユーザ定義のベースクラスは NotImplementedError を発生させます。</p>
<div class="highlight-python"><div class="highlight"><pre><span class="k">class</span> <span class="nc">BaseClass</span><span class="p">(</span><span class="nb">object</span><span class="p">):</span>
    <span class="sd">&quot;&quot;&quot;Defines the interface&quot;&quot;&quot;</span>
    <span class="k">def</span> <span class="nf">__init__</span><span class="p">(</span><span class="bp">self</span><span class="p">):</span>
        <span class="nb">super</span><span class="p">(</span><span class="n">BaseClass</span><span class="p">,</span> <span class="bp">self</span><span class="p">)</span><span class="o">.</span><span class="n">__init__</span><span class="p">()</span>
    <span class="k">def</span> <span class="nf">do_something</span><span class="p">(</span><span class="bp">self</span><span class="p">):</span>
        <span class="sd">&quot;&quot;&quot;The interface, not implemented&quot;&quot;&quot;</span>
        <span class="k">raise</span> <span class="ne">NotImplementedError</span><span class="p">(</span><span class="bp">self</span><span class="o">.</span><span class="n">__class__</span><span class="o">.</span><span class="n">__name__</span> <span class="o">+</span> <span class="s">&#39;.do_something&#39;</span><span class="p">)</span>

<span class="k">class</span> <span class="nc">SubClass</span><span class="p">(</span><span class="n">BaseClass</span><span class="p">):</span>
    <span class="sd">&quot;&quot;&quot;Implementes the interface&quot;&quot;&quot;</span>
    <span class="k">def</span> <span class="nf">do_something</span><span class="p">(</span><span class="bp">self</span><span class="p">):</span>
        <span class="sd">&quot;&quot;&quot;really does something&quot;&quot;&quot;</span>
        <span class="k">print</span> <span class="bp">self</span><span class="o">.</span><span class="n">__class__</span><span class="o">.</span><span class="n">__name__</span> <span class="o">+</span> <span class="s">&#39; doing something!&#39;</span>

<span class="n">SubClass</span><span class="p">()</span><span class="o">.</span><span class="n">do_something</span><span class="p">()</span>
<span class="n">BaseClass</span><span class="p">()</span><span class="o">.</span><span class="n">do_something</span><span class="p">()</span>
</pre></div>
</div>
<div class="highlight-python"><pre>$ python exceptions_NotImplementedError.py
SubClass doing something!
Traceback (most recent call last):
  File "exceptions_NotImplementedError.py", line 27, in &lt;module&gt;
    BaseClass().do_something()
  File "exceptions_NotImplementedError.py", line 18, in do_something
    raise NotImplementedError(self.__class__.__name__ + '.do_something')
NotImplementedError: BaseClass.do_something</pre>
</div>
<div class="admonition-see-also admonition seealso">
<p class="first admonition-title">See also</p>
<p class="last"><a class="reference internal" href="../abc/index.html#module-abc" title="抽象基底クラス"><tt class="xref py py-mod docutils literal"><span class="pre">abc</span></tt></a> - 抽象基底クラス</p>
</div>
</div>
<div class="section" id="oserror">
<h3>OSError<a class="headerlink" href="#oserror" title="Permalink to this headline">¶</a></h3>
<p>OSError は <a class="reference internal" href="../os/index.html#module-os" title="Portable access to operating system specific features."><tt class="xref py py-mod docutils literal"><span class="pre">os</span></tt></a> モジュールのエラークラスとして OS に特化した機能からエラーが返されるときに発生します。</p>
<div class="highlight-python"><div class="highlight"><pre><span class="kn">import</span> <span class="nn">os</span>

<span class="k">for</span> <span class="n">i</span> <span class="ow">in</span> <span class="nb">range</span><span class="p">(</span><span class="mi">10</span><span class="p">):</span>
    <span class="k">print</span> <span class="n">i</span><span class="p">,</span> <span class="n">os</span><span class="o">.</span><span class="n">ttyname</span><span class="p">(</span><span class="n">i</span><span class="p">)</span>
</pre></div>
</div>
<div class="highlight-python"><pre>$ python exceptions_OSError.py
0 /dev/ttys049
1
Traceback (most recent call last):
  File "exceptions_OSError.py", line 15, in &lt;module&gt;
    print i, os.ttyname(i)
OSError: [Errno 25] Inappropriate ioctl for device</pre>
</div>
</div>
<div class="section" id="overflowerror">
<span id="exceptions-overflowerror"></span><h3>OverflowError<a class="headerlink" href="#overflowerror" title="Permalink to this headline">¶</a></h3>
<p>数値の操作が変数のデータ型の最大値を超えるときに OverflowError が発生します。long int は巨大な値のためにより多くの領域を割り当てます。そのため、最終的には MemoryError が発生します。浮動小数点の例外は標準化されていないので浮動小数はチェックされません。必要に応じて普通の int 型から long 型へ変換されます。</p>
<div class="highlight-python"><div class="highlight"><pre><span class="kn">import</span> <span class="nn">sys</span>

<span class="k">print</span> <span class="s">&#39;Regular integer: (maxint=</span><span class="si">%s</span><span class="s">)&#39;</span> <span class="o">%</span> <span class="n">sys</span><span class="o">.</span><span class="n">maxint</span>
<span class="k">try</span><span class="p">:</span>
    <span class="n">i</span> <span class="o">=</span> <span class="n">sys</span><span class="o">.</span><span class="n">maxint</span> <span class="o">*</span> <span class="mi">3</span>
    <span class="k">print</span> <span class="s">&#39;No overflow for &#39;</span><span class="p">,</span> <span class="nb">type</span><span class="p">(</span><span class="n">i</span><span class="p">),</span> <span class="s">&#39;i =&#39;</span><span class="p">,</span> <span class="n">i</span>
<span class="k">except</span> <span class="ne">OverflowError</span><span class="p">,</span> <span class="n">err</span><span class="p">:</span>
    <span class="k">print</span> <span class="s">&#39;Overflowed at &#39;</span><span class="p">,</span> <span class="n">i</span><span class="p">,</span> <span class="n">err</span>

<span class="k">print</span>
<span class="k">print</span> <span class="s">&#39;Long integer:&#39;</span>
<span class="k">for</span> <span class="n">i</span> <span class="ow">in</span> <span class="nb">range</span><span class="p">(</span><span class="mi">0</span><span class="p">,</span> <span class="mi">100</span><span class="p">,</span> <span class="mi">10</span><span class="p">):</span>
    <span class="k">print</span> <span class="s">&#39;</span><span class="si">%2d</span><span class="s">&#39;</span> <span class="o">%</span> <span class="n">i</span><span class="p">,</span> <span class="il">2L</span> <span class="o">**</span> <span class="n">i</span>

<span class="k">print</span>
<span class="k">print</span> <span class="s">&#39;Floating point values:&#39;</span>
<span class="k">try</span><span class="p">:</span>
    <span class="n">f</span> <span class="o">=</span> <span class="mf">2.0</span><span class="o">**</span><span class="n">i</span>
    <span class="k">for</span> <span class="n">i</span> <span class="ow">in</span> <span class="nb">range</span><span class="p">(</span><span class="mi">100</span><span class="p">):</span>
        <span class="k">print</span> <span class="n">i</span><span class="p">,</span> <span class="n">f</span>
        <span class="n">f</span> <span class="o">=</span> <span class="n">f</span> <span class="o">**</span> <span class="mi">2</span>
<span class="k">except</span> <span class="ne">OverflowError</span><span class="p">,</span> <span class="n">err</span><span class="p">:</span>
    <span class="k">print</span> <span class="s">&#39;Overflowed after &#39;</span><span class="p">,</span> <span class="n">f</span><span class="p">,</span> <span class="n">err</span>
</pre></div>
</div>
<div class="highlight-python"><pre>$ python exceptions_OverflowError.py
Regular integer: (maxint=9223372036854775807)
No overflow for  &lt;type 'long'&gt; i = 27670116110564327421

Long integer:
 0 1
10 1024
20 1048576
30 1073741824
40 1099511627776
50 1125899906842624
60 1152921504606846976
70 1180591620717411303424
80 1208925819614629174706176
90 1237940039285380274899124224

Floating point values:
0 1.23794003929e+27
1 1.53249554087e+54
2 2.34854258277e+108
3 5.5156522631e+216
Overflowed after  5.5156522631e+216 (34, 'Result too large')</pre>
</div>
</div>
<div class="section" id="referenceerror">
<h3>ReferenceError<a class="headerlink" href="#referenceerror" title="Permalink to this headline">¶</a></h3>
<p>ガベージコレクトされたオブジェクトへ <a class="reference internal" href="../weakref/index.html#module-weakref" title="&quot;巨大な&quot; オブジェクトを参照して、他に非弱参照のオブジェクトがない場合にガベージコレクションの対象にする"><tt class="xref py py-mod docutils literal"><span class="pre">weakref</span></tt></a> プロキシを使用してアクセスするときに ReferenceError が発生します。</p>
<div class="highlight-python"><div class="highlight"><pre><span class="kn">import</span> <span class="nn">gc</span>
<span class="kn">import</span> <span class="nn">weakref</span>

<span class="k">class</span> <span class="nc">ExpensiveObject</span><span class="p">(</span><span class="nb">object</span><span class="p">):</span>
    <span class="k">def</span> <span class="nf">__init__</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">name</span><span class="p">):</span>
        <span class="bp">self</span><span class="o">.</span><span class="n">name</span> <span class="o">=</span> <span class="n">name</span>
    <span class="k">def</span> <span class="nf">__del__</span><span class="p">(</span><span class="bp">self</span><span class="p">):</span>
        <span class="k">print</span> <span class="s">&#39;(Deleting </span><span class="si">%s</span><span class="s">)&#39;</span> <span class="o">%</span> <span class="bp">self</span>

<span class="n">obj</span> <span class="o">=</span> <span class="n">ExpensiveObject</span><span class="p">(</span><span class="s">&#39;obj&#39;</span><span class="p">)</span>
<span class="n">p</span> <span class="o">=</span> <span class="n">weakref</span><span class="o">.</span><span class="n">proxy</span><span class="p">(</span><span class="n">obj</span><span class="p">)</span>

<span class="k">print</span> <span class="s">&#39;BEFORE:&#39;</span><span class="p">,</span> <span class="n">p</span><span class="o">.</span><span class="n">name</span>
<span class="n">obj</span> <span class="o">=</span> <span class="bp">None</span>
<span class="k">print</span> <span class="s">&#39;AFTER:&#39;</span><span class="p">,</span> <span class="n">p</span><span class="o">.</span><span class="n">name</span>
</pre></div>
</div>
<div class="highlight-python"><pre>$ python exceptions_ReferenceError.py
BEFORE: obj
(Deleting &lt;__main__.ExpensiveObject object at 0x1004704d0&gt;)
AFTER:
Traceback (most recent call last):
  File "exceptions_ReferenceError.py", line 26, in &lt;module&gt;
    print 'AFTER:', p.name
ReferenceError: weakly-referenced object no longer exists</pre>
</div>
</div>
<div class="section" id="runtimeerror">
<span id="exceptions-runtimeerror"></span><h3>RuntimeError<a class="headerlink" href="#runtimeerror" title="Permalink to this headline">¶</a></h3>
<p>他に適切な例外がないときに RuntimeError 例外が使用されます。インタープリタはこの例外を滅多に発生させませんが、ユーザコードによっては RuntimeError を発生させます。</p>
</div>
<div class="section" id="stopiteration">
<h3>StopIteration<a class="headerlink" href="#stopiteration" title="Permalink to this headline">¶</a></h3>
<p>イテレータが終了したときに、そのイテレータの <tt class="docutils literal"><span class="pre">next()</span></tt> メソッドは StopIteration を発生させます。この例外はエラーと見なされません。</p>
<div class="highlight-python"><div class="highlight"><pre><span class="n">l</span><span class="o">=</span><span class="p">[</span><span class="mi">0</span><span class="p">,</span><span class="mi">1</span><span class="p">,</span><span class="mi">2</span><span class="p">]</span>
<span class="n">i</span><span class="o">=</span><span class="nb">iter</span><span class="p">(</span><span class="n">l</span><span class="p">)</span>

<span class="k">print</span> <span class="n">i</span>
<span class="k">print</span> <span class="n">i</span><span class="o">.</span><span class="n">next</span><span class="p">()</span>
<span class="k">print</span> <span class="n">i</span><span class="o">.</span><span class="n">next</span><span class="p">()</span>
<span class="k">print</span> <span class="n">i</span><span class="o">.</span><span class="n">next</span><span class="p">()</span>
<span class="k">print</span> <span class="n">i</span><span class="o">.</span><span class="n">next</span><span class="p">()</span>
</pre></div>
</div>
<div class="highlight-python"><pre>$ python exceptions_StopIteration.py
&lt;listiterator object at 0x100460650&gt;
0
1
2
Traceback (most recent call last):
  File "exceptions_StopIteration.py", line 19, in &lt;module&gt;
    print i.next()
StopIteration</pre>
</div>
</div>
<div class="section" id="syntaxerror">
<h3>SyntaxError<a class="headerlink" href="#syntaxerror" title="Permalink to this headline">¶</a></h3>
<p>パーサが解析できないソースコードを見つけたときに SyntaxError が発生します。この例外はモジュールのインポート、 <tt class="docutils literal"><span class="pre">exec</span></tt> を実行したり、 <tt class="docutils literal"><span class="pre">eval()</span></tt> を呼び出したりするときに発生する可能性があります。例外の属性はこの例外を引き起こしたのがソースコードのどのテキストなのかを厳密に見つけるために使用されます。</p>
<div class="highlight-python"><div class="highlight"><pre><span class="k">try</span><span class="p">:</span>
    <span class="k">print</span> <span class="nb">eval</span><span class="p">(</span><span class="s">&#39;five times three&#39;</span><span class="p">)</span>
<span class="k">except</span> <span class="ne">SyntaxError</span><span class="p">,</span> <span class="n">err</span><span class="p">:</span>
    <span class="k">print</span> <span class="s">&#39;Syntax error </span><span class="si">%s</span><span class="s"> (</span><span class="si">%s</span><span class="s">-</span><span class="si">%s</span><span class="s">): </span><span class="si">%s</span><span class="s">&#39;</span> <span class="o">%</span> \
        <span class="p">(</span><span class="n">err</span><span class="o">.</span><span class="n">filename</span><span class="p">,</span> <span class="n">err</span><span class="o">.</span><span class="n">lineno</span><span class="p">,</span> <span class="n">err</span><span class="o">.</span><span class="n">offset</span><span class="p">,</span> <span class="n">err</span><span class="o">.</span><span class="n">text</span><span class="p">)</span>
    <span class="k">print</span> <span class="n">err</span>
</pre></div>
</div>
<div class="highlight-python"><pre>$ python exceptions_SyntaxError.py
Syntax error &lt;string&gt; (1-10): five times three
invalid syntax (&lt;string&gt;, line 1)</pre>
</div>
</div>
<div class="section" id="systemerror">
<h3>SystemError<a class="headerlink" href="#systemerror" title="Permalink to this headline">¶</a></h3>
<p>インタープリタそのものでエラーが発生しても正常に実行を継続する可能性があるときに SystemError が発生します。SystemErrors は、おそらくはインタープリタのバグを表し、メンテナへ報告すべきです。</p>
</div>
<div class="section" id="systemexit">
<span id="exceptions-systemexit"></span><h3>SystemExit<a class="headerlink" href="#systemexit" title="Permalink to this headline">¶</a></h3>
<p><tt class="docutils literal"><span class="pre">sys.exit()</span></tt> が呼び出されるとき、即時終了する代わりに SystemExit が発生します。これは <tt class="docutils literal"><span class="pre">try:finally</span></tt> ブロックのクリーンアップコードの実行、例外を捕捉するための(デバッガやテストフレームワークのような)特別な環境や処理を終了させないようにします。</p>
</div>
<div class="section" id="typeerror">
<span id="exceptions-typeerror"></span><h3>TypeError<a class="headerlink" href="#typeerror" title="Permalink to this headline">¶</a></h3>
<p>誤ったオブジェクトのデータ型を結合する、又は誤ったオブジェクトのデータ型で関数を呼び出すことで TypeErrors が発生します。</p>
<div class="highlight-python"><div class="highlight"><pre><span class="n">result</span> <span class="o">=</span> <span class="p">(</span><span class="s">&#39;tuple&#39;</span><span class="p">,)</span> <span class="o">+</span> <span class="s">&#39;string&#39;</span>
</pre></div>
</div>
<div class="highlight-python"><pre>$ python exceptions_TypeError.py
Traceback (most recent call last):
  File "exceptions_TypeError.py", line 12, in &lt;module&gt;
    result = ('tuple',) + 'string'
TypeError: can only concatenate tuple (not "str") to tuple</pre>
</div>
</div>
<div class="section" id="unboundlocalerror">
<h3>UnboundLocalError<a class="headerlink" href="#unboundlocalerror" title="Permalink to this headline">¶</a></h3>
<p>UnboundLocalError はローカル変数の名前に特化した NameError の一種です。</p>
<div class="highlight-python"><div class="highlight"><pre><span class="k">def</span> <span class="nf">throws_global_name_error</span><span class="p">():</span>
    <span class="k">print</span> <span class="n">unknown_global_name</span>

<span class="k">def</span> <span class="nf">throws_unbound_local</span><span class="p">():</span>
    <span class="n">local_val</span> <span class="o">=</span> <span class="n">local_val</span> <span class="o">+</span> <span class="mi">1</span>
    <span class="k">print</span> <span class="n">local_val</span>

<span class="k">try</span><span class="p">:</span>
    <span class="n">throws_global_name_error</span><span class="p">()</span>
<span class="k">except</span> <span class="ne">NameError</span><span class="p">,</span> <span class="n">err</span><span class="p">:</span>
    <span class="k">print</span> <span class="s">&#39;Global name error:&#39;</span><span class="p">,</span> <span class="n">err</span>

<span class="k">try</span><span class="p">:</span>
    <span class="n">throws_unbound_local</span><span class="p">()</span>
<span class="k">except</span> <span class="ne">UnboundLocalError</span><span class="p">,</span> <span class="n">err</span><span class="p">:</span>
    <span class="k">print</span> <span class="s">&#39;Local name error:&#39;</span><span class="p">,</span> <span class="n">err</span>
</pre></div>
</div>
<p>グローバルな NameError と UnboundLocal の違いはその名前の使用方法です。&#8221;local_val&#8221; という名前が式の左側に現れるのでローカル変数の名前として解釈されます。</p>
<div class="highlight-python"><pre>$ python exceptions_UnboundLocalError.py
Global name error: global name 'unknown_global_name' is not defined
Local name error: local variable 'local_val' referenced before assignment</pre>
</div>
</div>
<div class="section" id="unicodeerror">
<span id="exceptions-unicodeerror"></span><h3>UnicodeError<a class="headerlink" href="#unicodeerror" title="Permalink to this headline">¶</a></h3>
<p><tt class="xref py py-class docutils literal"><span class="pre">UnicodeError</span></tt> は <tt class="xref py py-class docutils literal"><span class="pre">ValueError</span></tt> のサブクラスでユニコードに関する問題で発生します。さらに <tt class="xref py py-class docutils literal"><span class="pre">UnicodeEncodeError</span></tt>, <tt class="xref py py-class docutils literal"><span class="pre">UnicodeDecodeError</span></tt> や <tt class="xref py py-class docutils literal"><span class="pre">UnicodeTranslateError</span></tt> といったサブクラスに分割されます。</p>
</div>
<div class="section" id="valueerror">
<span id="exceptions-valueerror"></span><h3>ValueError<a class="headerlink" href="#valueerror" title="Permalink to this headline">¶</a></h3>
<p>ある関数の受け取る値が正しい型で不正な値を持つときに ValueError が発生します。</p>
<div class="highlight-python"><div class="highlight"><pre><span class="k">print</span> <span class="nb">chr</span><span class="p">(</span><span class="mi">1024</span><span class="p">)</span>
</pre></div>
</div>
<div class="highlight-python"><pre>$ python exceptions_ValueError.py
Traceback (most recent call last):
  File "exceptions_ValueError.py", line 12, in &lt;module&gt;
    print chr(1024)
ValueError: chr() arg not in range(256)</pre>
</div>
</div>
<div class="section" id="zerodivisionerror">
<span id="exceptions-zerodivisionerror"></span><h3>ZeroDivisionError<a class="headerlink" href="#zerodivisionerror" title="Permalink to this headline">¶</a></h3>
<p>除算の分母がゼロのとき ZeroDivisionError が発生します。</p>
<div class="highlight-python"><div class="highlight"><pre><span class="k">print</span> <span class="mi">1</span><span class="o">/</span><span class="mi">0</span>
</pre></div>
</div>
<div class="highlight-python"><pre>$ python exceptions_ZeroDivisionError.py
Traceback (most recent call last):
  File "exceptions_ZeroDivisionError.py", line 12, in &lt;module&gt;
    print 1/0
ZeroDivisionError: integer division or modulo by zero</pre>
</div>
<span class="target" id="exceptions-warning"></span></div>
</div>
<div class="section" id="id5">
<h2>警告のカテゴリ<a class="headerlink" href="#id5" title="Permalink to this headline">¶</a></h2>
<p><a class="reference internal" href="../warnings/index.html#module-warnings" title="Deliver non-fatal alerts to the user about issues encountered when running a program."><tt class="xref py py-mod docutils literal"><span class="pre">warnings</span></tt></a> モジュールと一緒に使用する複数の例外もあります。</p>
<dl class="docutils">
<dt>Warning</dt>
<dd>全ての warnings のベースクラス</dd>
</dl>
<dl class="docutils">
<dt>UserWarning</dt>
<dd>ユーザコードから返される warnings のベースクラス</dd>
</dl>
<span class="target" id="exceptions-deprecationwarning"></span><dl class="docutils">
<dt>DeprecationWarning</dt>
<dd>今後はメンテナンスされない機能に使用される</dd>
</dl>
<dl class="docutils">
<dt>PendingDeprecationWarning</dt>
<dd>すぐに廃止予定の機能に使用される</dd>
</dl>
<dl class="docutils">
<dt>SyntaxWarning</dt>
<dd>怪しい構文に使用される</dd>
</dl>
<span class="target" id="exceptions-runtimewarning"></span><dl class="docutils">
<dt>RuntimeWarning</dt>
<dd>実行時に問題を引き起こすかもしれないイベントに使用される</dd>
</dl>
<dl class="docutils">
<dt>FutureWarning</dt>
<dd>言語又はライブラリがその後に変更されることに関して警告する</dd>
</dl>
<dl class="docutils">
<dt>ImportWarning</dt>
<dd>モジュールインポートの問題に関して警告する</dd>
</dl>
<dl class="docutils">
<dt>UnicodeWarning</dt>
<dd>ユニコードテキストの問題に関して警告する</dd>
</dl>
<div class="admonition-see-also admonition seealso">
<p class="first admonition-title">See also</p>
<dl class="last docutils">
<dt><a class="reference external" href="http://docs.python.org/library/exceptions.html">exceptions</a></dt>
<dd>本モジュールの標準ライブラリドキュメント</dd>
<dt><a class="reference internal" href="../warnings/index.html#module-warnings" title="Deliver non-fatal alerts to the user about issues encountered when running a program."><tt class="xref py py-mod docutils literal"><span class="pre">warnings</span></tt></a></dt>
<dd>エラーではない警告メッセージ</dd>
</dl>
</div>
</div>
</div>


    <div class="related">
      <h3>Navigation</h3>
      <ul>
        <li class="right" style="margin-right: 10px">
          <a href="../genindex.html" title="General Index"
             >index</a></li>
        <li class="right" >
          <a href="../py-modindex.html" title="Python Module Index"
             >modules</a> |</li>
        <li class="right" >
          <a href="../string_services.html" title="文字列サービス"
             >next</a> |</li>
        <li class="right" >
          <a href="../builtins.html" title="組み込みブジェクト"
             >previous</a> |</li>
        <li><a href="../contents.html">PyMOTW</a> &raquo;</li>
          <li><a href="../builtins.html" >組み込みブジェクト</a> &raquo;</li> 
      </ul>
    </div>



<div id="addthis"><a href="http://www.addthis.com/bookmark.php" onclick="addthis_url   = location.href; addthis_title = document.title; return addthis_click(this);" target="_blank"><img src="http://s7.addthis.com/static/btn/lg-share-en.gif" width="125" height="16" border="0" alt="Bookmark and Share" /></a><script type="text/javascript">var addthis_pub = "dhellmann";</script><script type="text/javascript" src="http://s7.addthis.com/js/widget.php?v=10"></script></div>



<!-- Disqus -->
<div id="disqus_wrapper">
<div id="disqus_thread"></div><script type="text/javascript" src="http://disqus.com/forums/doughellmann/embed.js"></script><noscript><a href="http://doughellmann.disqus.com/?url=ref">View the discussion thread.</a></noscript><a href="http://disqus.com" class="dsq-brlink">blog comments powered by <span class="logo-disqus">Disqus</span></a>
</div>

</div>

<div id="footer_ads">

    <p><script type="text/javascript"><!--
    google_ad_client = "pub-3205160560229413";
    google_ad_width = 728;
    google_ad_height = 90;
    google_ad_format = "728x90_as";
    google_ad_type = "text";
    //2007-10-21: www.doughellmann.com
    google_ad_channel = "9907726884";
    google_color_border = "FFFFFF";
    google_color_bg = "FFFFFF";
    google_color_link = "CC6714";
    google_color_text = "000000";
    google_color_url = "999999";
    google_ui_features = "rc:0";
    //-->
    </script>
    <script type="text/javascript"
      src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
    </script></p>
</div>

<div id="footer">
 
<p>
    &copy; Copyright Doug Hellmann.
    | <a href="http://creativecommons.org/licenses/by-nc-sa/3.0/us/" rel="license"><img alt="Creative Commons License" style="border-width:0; align: center;" width="80" height="15" src="http://i.creativecommons.org/l/by-nc-sa/3.0/us/80x15.png"/></a>
    | Last updated on Feb 17, 2013.
   | Created using <a href="http://sphinx.pocoo.org/">Sphinx</a>.
   | Design based on "Leaves" by <a href="http://smallpark.org">SmallPark</a>
</p>
   
<script src="http://www.google-analytics.com/urchin.js" type="text/javascript" />
<script type="text/javascript">
  _uacct = "UA-1847381-1";
  urchinTracker();
</script>

</div>

</div>


<!-- Disqus -->
<script type="text/javascript">
//<![CDATA[
(function() {
		var links = document.getElementsByTagName('a');
		var query = '?';
		for(var i = 0; i < links.length; i++) {
			if(links[i].href.indexOf('#disqus_thread') >= 0) {
				query += 'url' + i + '=' + encodeURIComponent(links[i].href) + '&';
			}
		}
		document.write('<script type="text/javascript" src="http://disqus.com/forums/doughellmann/get_num_replies.js' + query + '"></' + 'script>');
	})();
//]]>
</script>


</body>
</html>